# frozen_string_literal: true

class Champs::CarteChamp < ChampData
  # Default map location. Center of the World, ahm, France...
  DEFAULT_LON = 2.428462
  DEFAULT_LAT = 46.538192

  def legend_label?
    true
  end

  def html_label?
    false
  end

  # We are not using scopes here as we want to access
  # the following collections on unsaved records.
  def cadastres
    if cadastres?
      geo_areas.filter(&:cadastre?)
    else
      []
    end
  end

  def rpgs
    if rpg?
      geo_areas.filter(&:rpg?)
    else
      []
    end
  end

  def selections_utilisateur
    geo_areas.filter do |area|
      area.source == GeoArea.sources.fetch(:selection_utilisateur)
    end
  end

  def cadastres?
    type_de_champ.layer_enabled?(:cadastres)
  end

  def rpg?
    type_de_champ.layer_enabled?(:rpg)
  end

  def optional_layers
    type_de_champ.carte_optional_layers
  end

  def render_options
    { layers: optional_layers }
  end

  def position
    if dossier.present?
      dossier.geo_position
    else
      lon = DEFAULT_LON.to_s
      lat = DEFAULT_LAT.to_s
      zoom = "13"

      { lon: lon, lat: lat, zoom: zoom }
    end
  end

  def bounding_box
    if geo_areas.present?
      GeojsonService.bbox(type: 'FeatureCollection', features: geo_areas.map(&:to_feature))
    elsif dossier.present?
      point = dossier.geo_position
      GeojsonService.bbox(type: 'Feature', geometry: { type: 'Point', coordinates: [point[:lon], point[:lat]] })
    else
      GeojsonService.bbox(type: 'Feature', geometry: { type: 'Point', coordinates: [DEFAULT_LON, DEFAULT_LAT] })
    end
  end

  def to_feature_collection
    {
      type: 'FeatureCollection',
      id: stable_id,
      bbox: bounding_box,
      features: geo_areas.map(&:to_feature),
    }
  end

  def geometry?
    geo_areas.present?
  end

  # --- Static render ---------------------------------------------------------
  #
  # The image lives in its own `static_map` attachment rather than in
  # `piece_justificative_file`. It is not a pièce jointe: the usager did not
  # supply it, we generated it, and it exists only to be printed in the PDF
  # export. Keeping it under a separate name is what keeps it out of the pj
  # exports, the instructeur gallery, the watermarking and the auto-purge —
  # all of which walk `piece_justificative_file`.

  STATIC_MAP_FILENAME = 'carte.jpg'
  STATIC_MAP_CONTENT_TYPE = 'image/jpeg'
  STATIC_MAP_DIGEST_KEY = 'static_map_digest'

  # `static_map` is the ActiveStorage::Attached::One generated by
  # has_one_attached on ChampData; callers use `static_map.attached?`.

  def static_map_up_to_date?(digest)
    static_map.blob&.metadata&.dig(STATIC_MAP_DIGEST_KEY) == digest
  end

  def attach_static_map(io, digest:)
    blob = ActiveStorage::Blob.create_and_upload!(
      io:,
      filename: STATIC_MAP_FILENAME,
      content_type: STATIC_MAP_CONTENT_TYPE,
      # The image comes from us: running it through the virus scanner and the
      # blob processor would be pointless. `processed` short-circuits
      # AttachmentProcessorConcern.
      metadata: { 'processed' => true, 'virus_scan_result' => ActiveStorage::VirusScanner::SAFE, STATIC_MAP_DIGEST_KEY => digest }
    )

    # has_one_attached replaces on attach, so a re-render cannot pile up
    # attachments nor leave the champ imageless in between.
    static_map.attach(blob)
  end

  def purge_static_map
    static_map.purge if static_map.attached?
  end

  def selection_utilisateur_legacy_geo_area
    geometry = selection_utilisateur_legacy_geometry
    if geometry.present?
      GeoArea.new(
        source: GeoArea.sources.fetch(:selection_utilisateur),
        geometry: geometry
      )
    end
  end

  private

  def selection_utilisateur_legacy_geometry
    if selections_utilisateur.present?
      {
        type: 'MultiPolygon',
        coordinates: selections_utilisateur.filter do |selection_utilisateur|
          selection_utilisateur.geometry['type'] == 'Polygon'
        end.map do |selection_utilisateur|
          selection_utilisateur.geometry['coordinates']
        end,
      }
    else
      nil
    end
  end
end
